name: Build and deploy Python app to Azure Web App - ArguMentor

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies into backend folder
        run: |
          cd backend
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ArguMentor'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2F41789FBEBD4B0A83FD60851AA48FFD }}
          package: ./backend
